// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRf8SqVB2D4gNcIeXsHLiZGYOJs6yUwCg',
    appId: '1:478627294422:web:dca223f2bc7c21341bed77',
    messagingSenderId: '478627294422',
    projectId: 'todoapp0206',
    authDomain: 'todoapp0206.firebaseapp.com',
    storageBucket: 'todoapp0206.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPYn5E9JieyWqZje36LDkPiihXqTXGBGc',
    appId: '1:478627294422:android:e8565c27614993341bed77',
    messagingSenderId: '478627294422',
    projectId: 'todoapp0206',
    storageBucket: 'todoapp0206.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhba-_5r0FQeHo-mAiujKG9tvt06c1jIU',
    appId: '1:478627294422:ios:9aeb78a0835c88d91bed77',
    messagingSenderId: '478627294422',
    projectId: 'todoapp0206',
    storageBucket: 'todoapp0206.appspot.com',
    iosBundleId: 'com.example.todoapp',
  );
}
